FROM node:14.17

RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app

COPY package.json .
USER node
RUN npm install

COPY --chown=node:node . .
#RUN sudo chown -R 777 /app

CMD ["npm","run","start"]
