FROM node:14.17

USER node

WORKDIR /app
RUN chown -R 'node' /app

COPY package.json .
RUN npm install

COPY --chown=node:node . .
#RUN sudo chown -R 777 /app

CMD ["npm","run","start"]
